version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      -	echo "Entered build phase"
      - mvn clean install
  post_build:
    commands:
    
      - echo "Build completed"
artifacts:
  files:
    - deploy /**/*
  discard-paths: yes
